### ISSUE TITLE
Variable name discrepancy in Form A1a error checks

### ISSUE THREAD

**Issue by hewanadun** [naccdata/uniform-data-set#194]
@kgauthreaux 

Emily (@echeng06) noticed that Q22 - GOODFRIEND, Q32 - HEALACC variables in A1a error checks are defined as CLOSEFRND and HEALTHACC respectively in A1a questions_and_vars CSV. Which one is the correct? Could you please fix those too when you submit the PR for A1a header variables.

Thanks!

**Comment by echeng06** [comment]
Being handled in https://github.com/naccdata/uniform-data-set/pull/239
