### ISSUE TITLE
FRMDATE and LANG variables for optional forms

### ISSUE THREAD

**Issue by hewanadun** [naccdata/uniform-data-set#195]
@kgauthreaux For optional forms, FRMDATExx and LANGxx fields are marked as "Conditional" in questions_and_vars CSV, but the error checks state they cannot be blank.  I feel these should be defined as required fields in questions_and_vars, as the form header needs to be filled even when a form is optional and they also have to select a reason for not submitting the form. WDYT?

**Comment by hewanadun** [comment]
@kgauthreaux 
The way current "missingness" is defined in Q&V csv for other variables for optional forms is assuming the form is submitted. I think we should follow the same convention for header variables too.
If the form is not submitted, when we validate, we'll allow the all the variables except "MODEXX and XXNOT" to be blank.
Does that make sense?

**Comment by kgauthreaux** [comment]
@hewanadun okay, that is also okay for me as long as you have a way to note that the other header vars can be blank if the form is not submitted. All forms with a "XXNOT" var are not required

**Comment by hewanadun** [comment]
@kgauthreaux Yes, we are handling it in the code.
